version: "3"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - sqlite-data:/app/prisma
    restart: unless-stopped
    environment:
      - DATABASE_URL=file:/app/prisma/dev.db
      - NODE_ENV=production

volumes:
  sqlite-data:
    driver: local
