global:
  scrape_interval: 15s

scrape_configs:
  - job_name: "nextjs-app"
    static_configs:
      # If Next.js runs on host: - targets: ['host.docker.internal:3000']
      # If Next.js runs in Docker on same network: - targets: ['frontend-app:3000'] # Adjust service name if needed
      - targets: ["host.docker.internal:3000"] # Adjusted for running Next.js on host and Prometheus in Docker
    metrics_path: /api/metrics # The endpoint you created
